default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: ["default", "solid_queue_recurring", "backend", "webhooks", "*"]
      threads: 2
      processes: <%= Integer(ENV.fetch("JOB_CONCURRENCY") { Concurrent.physical_processor_count }) %>
      polling_interval: 1

development: *default
test: *default
beta: *default
staging: *default
production: *default
